# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /post/:title.html

# Setup
title:            Eniz Gülek
tagline:          'Front End Developer'
description:      "UX designer and product thinker. It's all about the experience."
url:              enzglk.github.io

author:
  name:           'Eniz Gülek'
  url:            https://twitter.com/enzglk

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/enzglk/hyde

collections:
- portfolio